<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>EldenRingUltrawideLauncher</AssemblyName>
    <RootNamespace>EldenRingUltrawideLauncher</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>

